name: Dev -> Staging -> Main PRs
on:
  workflow_dispatch:

jobs:
  create-staging-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@main

      - name: Create staging PR
        run: |
          gh pr create --base staging --head dev --title "🤖 Automated PR from dev to staging" --body "Automated PR from dev to staging" --reviewer ${{ env.PEER_REVIEWER }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PEER_REVIEWER: ${{ secrets.PEER_REVIEWER }}

  create-main-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@main

      - name: Create main PR
        run: |
          gh pr create --base main --head staging --title "🤖 Automated PR from staging to main" --body "Automated PR from staging to main" --reviewer ${{ env.MAIN_REVIEWER }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAIN_REVIEWER: ${{ secrets.MAIN_REVIEWER }}
