name: Release and Update Branches

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@main
        with:
          node-version: '>=20.12.2'

      - name: Install dependencies
        run: yarn

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: yarn audit signatures

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

  create-prs:
    name: Create Pull Requests
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout code
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Create Pull Request for dev branch
        run: |
          curl \
            -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{ "title": "🚀 Dev - downward merge from main", "head": "main", "base": "dev", "body": "Updating `dev` with the version changes" }' \
            https://api.github.com/repos/${{ github.repository }}/pulls

      - name: Create Pull Request for staging branch
        run: |
          curl \
            -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{ "title": "🚀 Staging - downward merge from main", "head": "main", "base": "staging", "body": "Updating `staging` with the version changes" }' \
            https://api.github.com/repos/${{ github.repository }}/pulls
